In [1]:
import pandas as pd
import numpy as np

In [2]:
movies=pd.read_csv('../dataset/tmdb_5000_movies.csv')
credits=pd.read_csv('../dataset/tmdb_5000_credits.csv')

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

Merging data for making it simple to handle.
so merging movies and credits (on the basis of title in columns).

In [5]:
movies = movies.merge(credits,on='title')

In [6]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

Since this is content based recommendation system.
we have to select the columns which actually affects our model.

In [7]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [8]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew','popularity','vote_average']]

In [9]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,popularity,vote_average
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",150.437577,7.2
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",139.082615,6.9
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",107.376788,6.3
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",112.312950,7.6
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",43.926995,6.1

In [10]:
movies.shape

(4809, 9)

In [11]:
movies.isnull().sum()

movie_id        0
title           0
overview        3
genres          0
keywords        0
cast            0
crew            0
popularity      0
vote_average    0
dtype: int64

In [12]:
movies.dropna(inplace=True)

In [13]:
movies['genres']

0       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3       [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
                              ...
4804    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4805    [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4806    [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4807                                                   []
4808                  [{"id": 99, "name": "Documentary"}]
Name: genres, Length: 4806, dtype: object

In [14]:
import ast

In [15]:
def correct_format(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L 
movies['genres'].apply(correct_format)

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4806, dtype: object

In [16]:
movies['genres']=movies['genres'].apply(correct_format)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,popularity,vote_average
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",150.437577,7.2
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",139.082615,6.9
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",107.376788,6.3
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",112.312950,7.6
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",43.926995,6.1

In [17]:
movies['keywords']=movies['keywords'].apply(correct_format)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,popularity,vote_average
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",150.437577,7.2
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",139.082615,6.9
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",107.376788,6.3
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",112.312950,7.6
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",43.926995,6.1

In [18]:
def correct_format_cast(text):
    L = []
    counter=0
    for i in ast.literal_eval(text):
        if counter !=3: 
        	L.append(i['name'])
        else:
            break
    return L
movies['cast']=movies['cast'].apply(correct_format)

In [19]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,popularity,vote_average
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",150.437577,7.2
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",139.082615,6.9
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",107.376788,6.3
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",112.312950,7.6
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",43.926995,6.1

In [20]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [21]:
movies['crew'] = movies['crew'].apply(fetch_director)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,popularity,vote_average
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron],150.437577,7.2
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski],139.082615,6.9
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes],107.376788,6.3
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan],112.312950,7.6
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton],43.926995,6.1

In [22]:
movies['overview']=movies['overview'].apply(lambda x : x.split() )

In [23]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,popularity,vote_average
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron],150.437577,7.2
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski],139.082615,6.9
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes],107.376788,6.3
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan],112.312950,7.6
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton],43.926995,6.1

In [24]:
movies['keywords']=movies['keywords'].apply(lambda x : [i.replace(" ","")for i in x] )
movies['genres']=movies['genres'].apply(lambda x : [i.replace(" ","")for i in x] )
movies['crew']=movies['crew'].apply(lambda x : [i.replace(" ","")for i in x] )
movies['cast']=movies['cast'].apply(lambda x : [i.replace(" ","")for i in x] )

In [25]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,popularity,vote_average
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],150.437577,7.2
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],139.082615,6.9
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes],107.376788,6.3
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],112.312950,7.6
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],43.926995,6.1

Creating tags for model.

In [26]:
movies['tags'] = movies['overview'] + movies['keywords'] + movies['genres'] + movies['crew'] + movies['cast']
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,popularity,vote_average,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],150.437577,7.2,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],139.082615,6.9,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes],107.376788,6.3,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],112.312950,7.6,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],43.926995,6.1,"[John, Carter, is, a, war-weary,, former, mili..."

In [27]:
newdf = movies[['movie_id','title','tags','popularity','vote_average']]
newdf.head()

,movie_id,title,tags,popularity,vote_average
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...",150.437577,7.2
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...",139.082615,6.9
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...",107.376788,6.3
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...",112.312950,7.6
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...",43.926995,6.1

In [28]:
newdf['tags'] = newdf['tags'].apply(lambda x: " ".join(x))

C:\Users\sarth\AppData\Local\Temp\ipykernel_23540\2433798782.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf['tags'] = newdf['tags'].apply(lambda x: " ".join(x))

In [29]:
newdf.head()

,movie_id,title,tags,popularity,vote_average
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,7.2
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,6.9
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,6.3
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,7.6
4,49529,John Carter,"John Carter is a war-weary, former military ca...",43.926995,6.1

In [30]:
newdf['tags'][2]

'A cryptic message from Bond’s past sends him on a trail to uncover a sinister organization. While M battles political forces to keep the secret service alive, Bond peels back the layers of deceit to reveal the terrible truth behind SPECTRE. spy basedonnovel secretagent sequel mi6 britishsecretservice unitedkingdom Action Adventure Crime SamMendes DanielCraig ChristophWaltz LéaSeydoux RalphFiennes MonicaBellucci BenWhishaw NaomieHarris DaveBautista AndrewScott RoryKinnear JesperChristensen AlessandroCremona StephanieSigman TenochHuerta AdrianaPaz DomenicoFortunato MarcoZingaro StefanoElfiDiClaudia IanBonar TamWilliams RichardBanham PipCarter SimonLenagan AlessandroBressanello MarcZinga BrigitteMillar AdelBencherif GediminasAdomaitis PeppeLanzetta FrancescoArca MatteoTaranto EmilioAniba BenitoSagredo DaiTabuchi GeorgeLasha SargonYelda AndyCheung ErickHayden OlegMirochnikov AntonioSalines MiloudMouradBenamara GidoSchimanski NigelBarber PatriceNaiambana StephaneCornicard GaryFannin SadaoUeda PhillipLaw WaiWong JosephBalderrama EijiMihara JunichiKajioka VictorSchefé HaraldWindisch TristanMatthiae DetlefBothe BodoFriesecke WilhemIben NoemiKrausz NoahSaavedra FrancisAttakpah MichaelGlantschnig MarlonBoess MarieWohlmuth LiliEpply KonstantinGerlach LaraParmiani UmitUlgen AmraMallassi ZiadAbaza WalidMumuni DerekHorsham NariBlair-Mangat MichaelWhite AdamMcGrady NaderDernaika PezhmaanAlinia JudiDench NeveGachev KarlFarrer KimAdis MaurisaSeleneColeman MatijaMondiMatović'

In [31]:
newdf['tags'] = newdf['tags'].apply(lambda x: x.lower())
newdf['tags'][2]

C:\Users\sarth\AppData\Local\Temp\ipykernel_23540\2292754541.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf['tags'] = newdf['tags'].apply(lambda x: x.lower())

'a cryptic message from bond’s past sends him on a trail to uncover a sinister organization. while m battles political forces to keep the secret service alive, bond peels back the layers of deceit to reveal the terrible truth behind spectre. spy basedonnovel secretagent sequel mi6 britishsecretservice unitedkingdom action adventure crime sammendes danielcraig christophwaltz léaseydoux ralphfiennes monicabellucci benwhishaw naomieharris davebautista andrewscott rorykinnear jesperchristensen alessandrocremona stephaniesigman tenochhuerta adrianapaz domenicofortunato marcozingaro stefanoelfidiclaudia ianbonar tamwilliams richardbanham pipcarter simonlenagan alessandrobressanello marczinga brigittemillar adelbencherif gediminasadomaitis peppelanzetta francescoarca matteotaranto emilioaniba benitosagredo daitabuchi georgelasha sargonyelda andycheung erickhayden olegmirochnikov antoniosalines miloudmouradbenamara gidoschimanski nigelbarber patricenaiambana stephanecornicard garyfannin sadaoueda philliplaw waiwong josephbalderrama eijimihara junichikajioka victorschefé haraldwindisch tristanmatthiae detlefbothe bodofriesecke wilhemiben noemikrausz noahsaavedra francisattakpah michaelglantschnig marlonboess mariewohlmuth liliepply konstantingerlach laraparmiani umitulgen amramallassi ziadabaza walidmumuni derekhorsham nariblair-mangat michaelwhite adammcgrady naderdernaika pezhmaanalinia judidench nevegachev karlfarrer kimadis maurisaselenecoleman matijamondimatović'

In [32]:
newdf['popularity']=newdf['popularity'].apply(lambda x: round(x,2))

C:\Users\sarth\AppData\Local\Temp\ipykernel_23540\3003457798.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf['popularity']=newdf['popularity'].apply(lambda x: round(x,2))

In [33]:
newdf.head()

,movie_id,title,tags,popularity,vote_average
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di...",150.44,7.2
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha...",139.08,6.9
2,206647,Spectre,a cryptic message from bond’s past sends him o...,107.38,6.3
3,49026,The Dark Knight Rises,following the death of district attorney harve...,112.31,7.6
4,49529,John Carter,"john carter is a war-weary, former military ca...",43.93,6.1

In [34]:
newdf.isnull().sum()

movie_id        0
title           0
tags            0
popularity      0
vote_average    0
dtype: int64

In [35]:
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [36]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    #again converting it into string
    return " ".join(y)
newdf['tags']= newdf['tags'].apply(stem)

C:\Users\sarth\AppData\Local\Temp\ipykernel_23540\123789120.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf['tags']= newdf['tags'].apply(stem)

In [37]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')
vectors = cv.fit_transform(newdf['tags']).toarray()

In [38]:
vectors[3]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [39]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zoo', 'zooeydeschanel', 'zoëkravitz'],
      dtype=object)

In [40]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(vectors)

array([[1.        , 0.06818182, 0.07644708, ..., 0.04307305, 0.        ,
        0.        ],
       [0.06818182, 1.        , 0.07644708, ..., 0.02153652, 0.        ,
        0.02383656],
       [0.07644708, 0.07644708, 1.        , ..., 0.02414726, 0.        ,
        0.        ],
       ...,
       [0.04307305, 0.02153652, 0.02414726, ..., 1.        , 0.04307305,
        0.0451754 ],
       [0.        , 0.        , 0.        , ..., 0.04307305, 1.        ,
        0.09534626],
       [0.        , 0.02383656, 0.        , ..., 0.0451754 , 0.09534626,
        1.        ]])

In [41]:
similar = cosine_similarity(vectors)

In [42]:
similar[2]

array([0.07644708, 0.07644708, 1.        , ..., 0.02414726, 0.        ,
       0.        ])

In [43]:
sorted(list(enumerate(similar[0])),reverse=True,key=lambda x : x[1])

[(0, 1.0000000000000002),
 (1216, 0.27028123880866767),
 (582, 0.23162743094465488),
 (2333, 0.22996655275195),
 (3730, 0.22498852128662872),
 (507, 0.22438727760202976),
 (539, 0.22305671869347438),
 (1920, 0.22010219462003333),
 (2409, 0.2175970699446223),
 (4048, 0.20751433915982237),
 (2786, 0.20695933859617893),
 (322, 0.20691022044226628),
 (577, 0.20100756305184242),
 (778, 0.19968076595771794),
 (1204, 0.19790977371009408),
 (61, 0.19596237883454903),
 (2971, 0.19462473604038075),
 (74, 0.1938287215142766),
 (151, 0.1928473039599675),
 (4192, 0.1928473039599675),
 (3608, 0.19145989526687088),
 (1089, 0.18540496217739155),
 (3999, 0.18463723646899916),
 (1444, 0.18281810603178267),
 (260, 0.1809806914982567),
 (973, 0.1809806914982567),
 (1194, 0.17837651700316892),
 (3327, 0.1776672636296754),
 (3675, 0.175919798853417),
 (1537, 0.17588161767036212),
 (495, 0.17407765595569785),
 (4405, 0.17407765595569785),
 (972, 0.17348855898381338),
 (4, 0.17056057308448835),
 (3538, 0.16898159235484367),
 (83, 0.16888013236829963),
 (2999, 0.16854996561581054),
 (27, 0.1682904582015223),
 (305, 0.1682904582015223),
 (184, 0.16685595311797868),
 (47, 0.16351748504193214),
 (942, 0.16262312563634837),
 (2204, 0.160930171455096),
 (172, 0.1599005372667078),
 (2075, 0.1599005372667078),
 (4336, 0.15909090909090912),
 (1275, 0.15745916432444343),
 (1329, 0.15745916432444343),
 (168, 0.15731330124142318),
 (3162, 0.15701373439577193),
 (595, 0.15559397856603546),
 (1071, 0.15392982399673985),
 (1321, 0.15386436372416595),
 (220, 0.15075567228888181),
 (529, 0.15075567228888181),
 (661, 0.15075567228888181),
 (36, 0.1492405014489273),
 (300, 0.1492405014489273),
 (931, 0.1487044791289829),
 (1201, 0.1487044791289829),
 (373, 0.14782809899727067),
 (2731, 0.14782809899727067),
 (41, 0.14777011582226215),
 (150, 0.14716573653773893),
 (1178, 0.14673479641335554),
 (1831, 0.1463423517512409),
 (4010, 0.14625448482542613),
 (139, 0.14519080172812554),
 (2515, 0.14506471329641488),
 (91, 0.14484136487558028),
 (1344, 0.14484136487558028),
 (342, 0.1446354779699756),
 (581, 0.14245072057454744),
 (1673, 0.1421338109037403),
 (1982, 0.14126448280440335),
 (158, 0.1411569346481171),
 (56, 0.1399731277389636),
 (1479, 0.13977653617040256),
 (3354, 0.13762047064079508),
 (838, 0.1374416265488099),
 (2760, 0.13623731522826651),
 (208, 0.13483997249264842),
 (1273, 0.13483997249264842),
 (1383, 0.13483997249264842),
 (1396, 0.13402192668680965),
 (127, 0.1340050420345616),
 (94, 0.13336626734231613),
 (187, 0.13336626734231613),
 (1938, 0.13336626734231613),
 (937, 0.1332504477222565),
 (1327, 0.1315903389919538),
 (1488, 0.1315903389919538),
 (2970, 0.1315903389919538),
 (557, 0.1305582419667734),
 (1355, 0.1305582419667734),
 (149, 0.13005121775247103),
 (461, 0.1292719224987548),
 (3409, 0.1292719224987548),
 (1056, 0.12921914767618442),
 (4538, 0.12921914767618442),
 (311, 0.1292191476761844),
 (1965, 0.12892415701965754),
 (3781, 0.128564869306645),
 (67, 0.12792042981336627),
 (513, 0.12792042981336627),
 (413, 0.12741179785940637),
 (568, 0.12741179785940637),
 (46, 0.1266600992762247),
 (157, 0.1257389226923863),
 (490, 0.1257389226923863),
 (1301, 0.1257389226923863),
 (1945, 0.1256297269074015),
 (108, 0.12543630150106364),
 (17, 0.12436708454077278),
 (502, 0.12424730498438732),
 (275, 0.12392039927415242),
 (859, 0.12392039927415242),
 (2169, 0.12392039927415242),
 (2496, 0.12392039927415242),
 (4079, 0.12392039927415242),
 (1322, 0.12351231781710247),
 (2584, 0.12309149097933275),
 (3982, 0.12309149097933275),
 (579, 0.12227899701112964),
 (294, 0.12227899701112963),
 (1808, 0.12227899701112963),
 (1297, 0.12196734422726127),
 (2133, 0.12196734422726127),
 (95, 0.12196734422726126),
 (777, 0.12087344460380703),
 (31, 0.1207011373963169),
 (1560, 0.1207011373963169),
 (2181, 0.1207011373963169),
 (668, 0.12060453783110546),
 (1373, 0.12060453783110546),
 (26, 0.11980845957463077),
 (843, 0.11918282365569904),
 (2686, 0.11918282365569904),
 (3628, 0.11918282365569904),
 (505, 0.11826247919781653),
 (2378, 0.11826247919781653),
 (111, 0.11776030079682895),
 (589, 0.11776030079682895),
 (2873, 0.11776030079682895),
 (3622, 0.11772040233700279),
 (206, 0.11725441178024137),
 (4230, 0.11631052629980887),
 (1299, 0.11631052629980886),
 (2652, 0.1160517706371319),
 (122, 0.11495012246792571),
 (1086, 0.11495012246792571),
 (1220, 0.11487593716012254),
 (466, 0.11396057645963795),
 (476, 0.11396057645963795),
 (773, 0.11396057645963795),
 (935, 0.11396057645963795),
 (7, 0.11306675421666137),
 (84, 0.11306675421666137),
 (102, 0.11306675421666137),
 (1741, 0.11306675421666137),
 (1878, 0.11306675421666137),
 (1715, 0.11306675421666136),
 (4348, 0.11306675421666136),
 (138, 0.11236664374387369),
 (1015, 0.11236664374387369),
 (2450, 0.11236664374387369),
 (3235, 0.11236664374387369),
 (487, 0.11197850219117086),
 (1774, 0.11197850219117086),
 (4673, 0.11197850219117086),
 (72, 0.11113855611859677),
 (1401, 0.11113855611859677),
 (2372, 0.11113855611859677),
 (1004, 0.11009637651263605),
 (1047, 0.11009637651263605),
 (1658, 0.11009637651263605),
 (549, 0.10994987428338562),
 (2480, 0.1096908636190696),
 (4000, 0.1096908636190696),
 (654, 0.10889310129609417),
 (454, 0.10879853497231115),
 (3376, 0.10830607221477648),
 (160, 0.10770505460691618),
 (14, 0.107682623063487),
 (126, 0.107682623063487),
 (166, 0.107682623063487),
 (438, 0.107682623063487),
 (3212, 0.10726454129012915),
 (900, 0.10660035817780522),
 (1617, 0.10660035817780522),
 (2789, 0.10660035817780522),
 (134, 0.10660035817780521),
 (167, 0.10660035817780521),
 (249, 0.10660035817780521),
 (786, 0.10660035817780521),
 (1274, 0.10660035817780521),
 (2148, 0.10660035817780521),
 (1002, 0.10586770098608783),
 (368, 0.10497277621629561),
 (678, 0.10497277621629561),
 (1096, 0.10497277621629561),
 (1833, 0.10497277621629561),
 (4468, 0.10497277621629561),
 (536, 0.10453025125088636),
 (3147, 0.1044465935734187),
 (1497, 0.10444659357341869),
 (2331, 0.1037571695799112),
 (228, 0.10353942082032278),
 (432, 0.10353942082032278),
 (740, 0.10353942082032278),
 (1512, 0.10353942082032278),
 (2284, 0.10353942082032278),
 (3630, 0.10353942082032278),
 (50, 0.10341753799900383),
 (1031, 0.10341753799900383),
 (2817, 0.10341753799900383),
 (467, 0.10257624248277727),
 (870, 0.10257624248277727),
 (87, 0.1019294382875251),
 (422, 0.1019294382875251),
 (483, 0.1019294382875251),
 (238, 0.10176802973291377),
 (420, 0.10163945352271772),
 (85, 0.10154529930749041),
 (2634, 0.10112997936948631),
 (2674, 0.10112997936948631),
 (3721, 0.10112997936948631),
 (43, 0.10072787050317253),
 (123, 0.10072787050317253),
 (2547, 0.10072787050317253),
 (3093, 0.10072787050317253),
 (232, 0.10050378152592121),
 (332, 0.10050378152592121),
 (544, 0.10050378152592121),
 (781, 0.10050378152592121),
 (2060, 0.10050378152592121),
 (2865, 0.10050378152592121),
 (3498, 0.10050378152592121),
 (4097, 0.10050378152592121),
 (4777, 0.10050378152592121),
 (81, 0.09988907373180403),
 (229, 0.09988907373180403),
 (3309, 0.09984038297885897),
 (1574, 0.09928550884822428),
 (889, 0.09927330486454494),
 (148, 0.09913631941932194),
 (236, 0.09913631941932194),
 (2741, 0.09913631941932194),
 (3407, 0.09913631941932194),
 (3428, 0.09913631941932194),
 (3926, 0.09913631941932194),
 (997, 0.09897594780811197),
 (1418, 0.09897594780811197),
 (307, 0.09883693657685838),
 (627, 0.09869275424396534),
 (1348, 0.09869275424396534),
 (2521, 0.09869275424396534),
 (3083, 0.09869275424396534),
 (4203, 0.09869275424396534),
 (199, 0.09813358399735746),
 (270, 0.09813358399735746),
 (2099, 0.09813358399735746),
 (2439, 0.09813358399735746),
 (939, 0.09811049102515929),
 (1616, 0.0978231976089037),
 (2175, 0.0978231976089037),
 (2247, 0.0978231976089037),
 (4019, 0.0978231976089037),
 (2106, 0.09731236802019037),
 (754, 0.09656090991705352),
 (814, 0.09656090991705352),
 (1037, 0.09656090991705352),
 (1237, 0.09656090991705352),
 (2072, 0.09656090991705352),
 (182, 0.09651142956027287),
 (572, 0.09651142956027287),
 (1455, 0.09651142956027287),
 (808, 0.09642365197998373),
 (1156, 0.09642365197998373),
 (1524, 0.09642365197998373),
 (3621, 0.09642365197998373),
 (3663, 0.09642365197998373),
 (4198, 0.09642365197998373),
 (52, 0.09572994763343545),
 (75, 0.09534625892455924),
 (223, 0.09534625892455924),
 (1290, 0.09534625892455924),
 (262, 0.09496714704969828),
 (425, 0.09496714704969828),
 (653, 0.09430419201928972),
 (1501, 0.09430419201928972),
 (2762, 0.09430419201928972),
 (3839, 0.09430419201928972),
 (170, 0.09422229518055114),
 (692, 0.09422229518055114),
 (1405, 0.09422229518055114),
 (1496, 0.09422229518055114),
 (2498, 0.09422229518055114),
 (687, 0.09417632186960223),
 (787, 0.09417632186960223),
 (1614, 0.09417632186960223),
 (3340, 0.09417632186960223),
 (3874, 0.09417632186960223),
 (3441, 0.09349469900084573),
 (28, 0.09304842103984709),
 (203, 0.09304842103984709),
 (449, 0.09304842103984709),
 (1823, 0.09304842103984709),
 (189, 0.09231861823449956),
 (3055, 0.09231861823449956),
 (239, 0.09208868358546966),
 (491, 0.09208868358546966),
 (68, 0.09196009797434057),
 (295, 0.09196009797434057),
 (472, 0.09196009797434057),
 (632, 0.09196009797434057),
 (1097, 0.09196009797434057),
 (1109, 0.09196009797434057),
 (1145, 0.09196009797434057),
 (1158, 0.09196009797434057),
 (1294, 0.09196009797434057),
 (1771, 0.09196009797434057),
 (2253, 0.09196009797434057),
 (2556, 0.09196009797434057),
 (3152, 0.09196009797434057),
 (3620, 0.09196009797434057),
 (3783, 0.09196009797434057),
 (21, 0.09090909090909091),
 (131, 0.09090909090909091),
 (510, 0.09090909090909091),
 (988, 0.09090909090909091),
 (1113, 0.09090909090909091),
 (2787, 0.09045340337332909),
 (4472, 0.09045340337332909),
 (1775, 0.09009374626955591),
 (4545, 0.09009374626955591),
 (10, 0.08989331499509895),
 (480, 0.08989331499509895),
 (2241, 0.08989331499509895),
 (3755, 0.08989331499509895),
 (3935, 0.08989331499509895),
 (5, 0.08945703337056415),
 (213, 0.08945703337056415),
 (312, 0.08891084489487741),
 (535, 0.08891084489487741),
 (643, 0.08891084489487741),
 (1082, 0.08891084489487741),
 (1195, 0.08891084489487741),
 (2592, 0.08891084489487741),
 (2650, 0.08891084489487741),
 (3008, 0.08891084489487741),
 (153, 0.0888336318148377),
 (1575, 0.0886968593983624),
 (2323, 0.0886968593983624),
 (2456, 0.0886968593983624),
 (2645, 0.0886968593983624),
 (3736, 0.0886968593983624),
 (3901, 0.0886968593983624),
 (4018, 0.0886968593983624),
 (4256, 0.0886968593983624),
 (4490, 0.0886968593983624),
 (1439, 0.08822308415507318),
 (266, 0.0879598994267085),
 (371, 0.0879598994267085),
 (3255, 0.0879598994267085),
 (3611, 0.0879598994267085),
 (4180, 0.0879598994267085),
 (18, 0.0876249546540977),
 (363, 0.0876249546540977),
 (121, 0.08703882797784893),
 (193, 0.08703882797784893),
 (410, 0.08703882797784893),
 (660, 0.08703882797784893),
 (1077, 0.08703882797784893),
 (1446, 0.08703882797784893),
 (1686, 0.08703882797784893),
 (1727, 0.08703882797784893),
 (2161, 0.08703882797784893),
 (2820, 0.08703882797784893),
 (3634, 0.08703882797784893),
 (4135, 0.08703882797784893),
 (4205, 0.08703882797784893),
 (4331, 0.08703882797784893),
 (4403, 0.08703882797784893),
 (230, 0.08646430798325933),
 (1692, 0.0861460984507896),
 (2527, 0.0861460984507896),
 (3140, 0.0861460984507896),
 (4343, 0.0861460984507896),
 (256, 0.08547043234472845),
 (624, 0.08547043234472845),
 (715, 0.08547043234472845),
 (791, 0.08547043234472845),
 (1721, 0.08547043234472845),
 (2053, 0.08547043234472845),
 (2396, 0.08547043234472845),
 (3483, 0.08547043234472845),
 (3537, 0.08547043234472845),
 (3954, 0.08547043234472845),
 (1487, 0.08534859274986485),
 (334, 0.08528028654224418),
 (1846, 0.08528028654224418),
 (3389, 0.08528028654224418),
 (3553, 0.08528028654224418),
 (2570, 0.0848066914440948),
 (11, 0.0844400661841498),
 (419, 0.0844400661841498),
 (445, 0.0844400661841498),
 (898, 0.0844400661841498),
 (1906, 0.0844400661841498),
 (785, 0.08427498280790527),
 (799, 0.08427498280790527),
 (200, 0.08398387664337814),
 (794, 0.08398387664337814),
 (1280, 0.08398387664337814),
 (2093, 0.08398387664337814),
 (2562, 0.08398387664337814),
 (2651, 0.08398387664337814),
 (2868, 0.08398387664337814),
 (2957, 0.08398387664337814),
 (3448, 0.08398387664337814),
 (301, 0.08375315127160099),
 (278, 0.08362420100070908),
 (331, 0.08362420100070908),
 (412, 0.08362420100070908),
 (596, 0.08362420100070908),
 (602, 0.08362420100070908),
 (2488, 0.08362420100070908),
 (2713, 0.08362420100070908),
 (3462, 0.08362420100070908),
 (3720, 0.08362420100070908),
 (3881, 0.08362420100070908),
 (4516, 0.08362420100070908),
 (234, 0.08283153665625823),
 (508, 0.08283153665625823),
 (1701, 0.08283153665625823),
 (2115, 0.0827379240401869),
 (319, 0.08257228238447704),
 (1259, 0.08257228238447704),
 (1306, 0.08257228238447704),
 (1480, 0.08257228238447704),
 (2216, 0.08257228238447704),
 (274, 0.08215419219227854),
 (217, 0.08206099398622183),
 (1175, 0.08206099398622183),
 (2035, 0.08206099398622183),
 (479, 0.08175874252096607),
 (827, 0.08131156281817417),
 (1233, 0.08131156281817417),
 (2354, 0.08131156281817417),
 (209, 0.08122955416108235),
 (233, 0.08122955416108235),
 (244, 0.08122955416108235),
 (356, 0.08122955416108235),
 (1745, 0.08122955416108235),
 (2251, 0.08122955416108235),
 (143, 0.08058229640253803),
 (330, 0.08058229640253803),
 (383, 0.08058229640253803),
 (752, 0.08058229640253803),
 (1276, 0.08058229640253803),
 (1357, 0.08058229640253803),
 (2109, 0.08058229640253803),
 (2792, 0.08058229640253803),
 (2796, 0.08058229640253803),
 (3556, 0.08058229640253803),
 (4353, 0.08058229640253803),
 (4502, 0.08058229640253803),
 (3368, 0.08026441628216505),
 (141, 0.0799502686333539),
 (389, 0.0799502686333539),
 (1474, 0.0799502686333539),
 (1854, 0.0799502686333539),
 (3135, 0.0799502686333539),
 (3678, 0.0799502686333539),
 (4754, 0.0799502686333539),
 (243, 0.07987230638308718),
 (671, 0.07987230638308718),
 (746, 0.07987230638308718),
 (1832, 0.07987230638308718),
 (2363, 0.07987230638308718),
 (2740, 0.07987230638308718),
 (3905, 0.07987230638308718),
 (813, 0.07918075824648958),
 (1030, 0.07918075824648958),
 (1634, 0.07901744265512675),
 (745, 0.0787295821622217),
 (1589, 0.0787295821622217),
 (1756, 0.0787295821622217),
 (2644, 0.0787295821622217),
 (2660, 0.0787295821622217),
 (4560, 0.0787295821622217),
 (103, 0.07850686719788597),
 (1639, 0.07850686719788597),
 (129, 0.0778498944161523),
 (473, 0.0778498944161523),
 (541, 0.0778498944161523),
 (1019, 0.0778498944161523),
 (2968, 0.0778498944161523),
 (3728, 0.0778498944161523),
 (4587, 0.0778498944161523),
 (4654, 0.0778498944161523),
 (4737, 0.0778498944161523),
 (263, 0.07756315349925287),
 (292, 0.07756315349925287),
 (511, 0.07756315349925287),
 (564, 0.07756315349925287),
 (960, 0.07756315349925287),
 (980, 0.07756315349925287),
 (1378, 0.07756315349925287),
 (1586, 0.07756315349925287),
 (1928, 0.07756315349925287),
 (3301, 0.07756315349925287),
 (3322, 0.07756315349925287),
 (4657, 0.07756315349925287),
 (3, 0.07733602811121826),
 (2448, 0.07733602811121826),
 (734, 0.07720914364821829),
 (1011, 0.07720914364821829),
 (45, 0.07658395810674837),
 (2386, 0.07653459686532839),
 (2, 0.07644707871564382),
 (775, 0.07644707871564382),
 (863, 0.07644707871564382),
 (878, 0.07644707871564382),
 (922, 0.07644707871564382),
 (1142, 0.07644707871564382),
 (2167, 0.07644707871564382),
 (2400, 0.07644707871564382),
 (2583, 0.07644707871564382),
 (2661, 0.07644707871564382),
 (4626, 0.07644707871564382),
 (63, 0.07597371763975862),
 (169, 0.07597371763975862),
 (768, 0.07597371763975862),
 (4506, 0.07597371763975862),
 (9, 0.07537783614444091),
 (23, 0.07537783614444091),
 (88, 0.07537783614444091),
 (142, 0.07537783614444091),
 (369, 0.07537783614444091),
 (400, 0.07537783614444091),
 (899, 0.07537783614444091),
 (901, 0.07537783614444091),
 (1139, 0.07537783614444091),
 (1249, 0.07537783614444091),
 (1519, 0.07537783614444091),
 (1573, 0.07537783614444091),
 (1747, 0.07537783614444091),
 (1884, 0.07537783614444091),
 (2274, 0.07537783614444091),
 (2304, 0.07537783614444091),
 (2445, 0.07537783614444091),
 (2671, 0.07537783614444091),
 (2715, 0.07537783614444091),
 (2856, 0.07537783614444091),
 (2880, 0.07537783614444091),
 (3102, 0.07537783614444091),
 (3470, 0.07537783614444091),
 (3527, 0.07537783614444091),
 (3560, 0.07537783614444091),
 (3949, 0.07537783614444091),
 (4279, 0.07537783614444091),
 (4316, 0.07537783614444091),
 (4641, 0.07537783614444091),
 (486, 0.07500375028127344),
 (1783, 0.07479575920067658),
 (125, 0.07460470969529907),
 (12, 0.07435223956449145),
 (306, 0.07435223956449145),
 (315, 0.07435223956449145),
 (349, 0.07435223956449145),
 (920, 0.07435223956449145),
 (1166, 0.07435223956449145),
 (1207, 0.07435223956449145),
 (1942, 0.07435223956449145),
 (3028, 0.07435223956449145),
 (3233, 0.07435223956449145),
 (3297, 0.07435223956449145),
 (3764, 0.07435223956449145),
 (3816, 0.07435223956449145),
 (3851, 0.07435223956449145),
 (190, 0.07422696190252054),
 (222, 0.07422696190252054),
 (19, 0.07367094686837573),
 (48, 0.07367094686837573),
 (612, 0.07367094686837573),
 (618, 0.07367094686837573),
 (1346, 0.07367094686837573),
 (1828, 0.07367094686837573),
 (35, 0.07336739820667779),
 (325, 0.07336739820667779),
 (457, 0.07336739820667779),
 (894, 0.07336739820667779),
 (1027, 0.07336739820667779),
 (1749, 0.07336739820667779),
 (2128, 0.07336739820667779),
 (2295, 0.07336739820667779),
 (164, 0.07336739820667777),
 (1924, 0.07312724241271307),
 (3978, 0.07312724241271307),
 (4492, 0.07312724241271307),
 (51, 0.07259540086406277),
 (501, 0.07259540086406277),
 (1898, 0.07259540086406277),
 (33, 0.07242068243779014),
 (1523, 0.07242068243779014),
 (2683, 0.07242068243779014),
 (3805, 0.07242068243779014),
 (812, 0.07207499701564472),
 (1305, 0.07207499701564472),
 (1534, 0.07207499701564471),
 (32, 0.07156562669645132),
 (607, 0.07156562669645132),
 (1926, 0.07156562669645132),
 (2005, 0.07156562669645132),
 (854, 0.07150969419341943),
 (1032, 0.07150969419341943),
 (1161, 0.07150969419341943),
 (1181, 0.07150969419341943),
 (4268, 0.07150969419341943),
 (4558, 0.07150969419341943),
 (4624, 0.07150969419341943),
 (534, 0.07106690545187015),
 (1530, 0.07106690545187015),
 (2712, 0.07106690545187015),
 (2801, 0.07106690545187015),
 (2861, 0.07106690545187015),
 (3180, 0.07106690545187015),
 (3431, 0.07106690545187015),
 (3832, 0.07106690545187015),
 (4011, 0.07106690545187015),
 (4236, 0.07106690545187015),
 (105, 0.07063224140220167),
 (241, 0.07063224140220167),
 (362, 0.07063224140220167),
 (402, 0.07063224140220167),
 (587, 0.07063224140220167),
 (1080, 0.07063224140220167),
 (2018, 0.07063224140220167),
 (2163, 0.07063224140220167),
 (3164, 0.07063224140220167),
 (403, 0.07057846732405855),
 (2203, 0.07057846732405855),
 (3331, 0.07029019463944167),
 (286, 0.07009996372327816),
 (1659, 0.07009996372327816),
 (4429, 0.07009996372327816),
 (37, 0.06978631577988531),
 (227, 0.06978631577988531),
 (235, 0.06978631577988531),
 (242, 0.06978631577988531),
 (492, 0.06978631577988531),
 (547, 0.06978631577988531),
 (855, 0.06978631577988531),
 (1269, 0.06978631577988531),
 (1293, 0.06978631577988531),
 (2851, 0.06978631577988531),
 (2938, 0.06978631577988531),
 (3285, 0.06978631577988531),
 (38, 0.06963106238227913),
 (246, 0.06963106238227913),
 (1282, 0.06963106238227913),
 (381, 0.06917144638660747),
 (1664, 0.06917144638660747),
 (1770, 0.06917144638660747),
 (2165, 0.06917144638660747),
 (2297, 0.06917144638660747),
 (2877, 0.06917144638660747),
 (3117, 0.06917144638660747),
 (4431, 0.06917144638660747),
 (39, 0.06897007348075543),
 (70, 0.06897007348075543),
 (98, 0.06897007348075543),
 (112, 0.06897007348075543),
 (207, 0.06897007348075543),
 (219, 0.06897007348075543),
 (680, 0.06897007348075543),
 (1367, 0.06897007348075543),
 (2235, 0.06897007348075543),
 (2449, 0.06897007348075543),
 (2852, 0.06897007348075543),

In [44]:
def recommender(movie):
    movie_index = newdf[newdf['title'] == movie ].index[0]
    distances =similar[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x : x[1])[1:10]
    for i in movies_list:
        
        print(newdf.iloc[i[0]].title)

In [45]:
recommender("Pirates of the Caribbean: At World's End")

Pirates of the Caribbean: Dead Man's Chest
Pirates of the Caribbean: The Curse of the Black Pearl
Pirates of the Caribbean: On Stranger Tides
20,000 Leagues Under the Sea
Life of Pi
The Black Hole
The Pirates! In an Adventure with Scientists!
Puss in Boots
The Host

In [46]:
recommender("Titanic")

The Bounty
The Notebook
Under the Same Moon
Ghost Ship
Poseidon
Pirates of the Caribbean: On Stranger Tides
Master and Commander: The Far Side of the World
The Switch
Rent

In [47]:
import pickle
pickle.dump(newdf,open('movies_list.pkl','wb'))

In [48]:
pickle.dump(similar,open('similar_movies.pkl','wb'))

In [53]:
pickle.dump(movies,open('movies_data.pkl','wb'))